# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: "Run npm i"
      run: npm i
      
    - name: Build documentation
      run: npm run docs:build
    
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.1.0
      with:
        # Arguments for the git add command
        add: "-A"
        # The name of the user that will be displayed as the author of the commit
        author_name: "Benjamin Horne" 
        # The email of the user that will be displayed as the author of the commit
        author_email: "benjamin.horne@keenmate.com"
        # The directory where your repository is located. You should use actions/checkout first to set it up
        # cwd: # optional, default is .
        # Whether to use the force option on git add, in order to bypass eventual gitignores
        # force: # optional, default is false
        # The message for the commit
        message: "New version created"
        # Name of the branch to use, if different from the one that triggered the workflow
        ref: gh-pages# optional

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token:  $\{{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        # repository: # optional, default is 
        # Destination branch to push changes
        branch: "gh-pages"
        # Determines if force push is used
        force: true # optional
        # Directory to change to before pushing.
        directory: "docs/.vuepress/dist" # optional, default is .
